services:
  server:
    user: root
    build:
      context: .
    env_file:
      - stack.env
    volumes:
      - courses:/usr/src/app/public/courses
      - data:/usr/src/app/data
    ports:
      - 6547:6547

volumes:
  courses:
  data: